BlockInput(1)
Global $main = WinActivate("网上股票交易系统5.0")
WinSetState($main, "", @SW_SHOW)
ControlClick($main, "", "[CLASS:SysTreeView32; INSTANCE:1]", "left", 1, 77, 190)
Sleep(1000)
ControlClick($main, "", "[CLASS:ToolbarWindow32; INSTANCE:1]", "left", 1, 164, 22)
Sleep(1000)
ControlClick($main, "", "[CLASS:CVirtualGridCtrl; INSTANCE:1]")
Sleep(100)
Send("^c")
Sleep(100)
Dim $text = ClipGet()
Dim $zichan = ControlGetText($main, "", "[CLASS:Static; INSTANCE:16]")
Dim $shizhi = ControlGetText($main, "", "[CLASS:Static; INSTANCE:15]")
Dim $kequ = ControlGetText($main, "", "[CLASS:Static; INSTANCE:14]")
Dim $keyong = ControlGetText($main, "", "[CLASS:Static; INSTANCE:10]")
Dim $dongjie = ControlGetText($main, "", "[CLASS:Static; INSTANCE:9]")
Dim $yue = ControlGetText($main, "", "[CLASS:Static; INSTANCE:8]")
ConsoleWrite($zichan & @TAB & $shizhi & @TAB & $kequ & @TAB & $keyong & @TAB & $dongjie & @TAB & $yue & @LF)
ConsoleWrite($text)
WinSetState($main, "", @SW_HIDE)
BlockInput(0)
